export const FETCH_CURRENCY_BY_ABBREVIATION_SUCCESS = 'FETCH_CURRENCY_BY_ABBREVIATION_SUCCESS';
export const FETCH_CURRENCY_BY_ABBREVIATION_ERROR = 'FETCH_CURRENCY_BY_ABBREVIATION_ERROR';

export const FETCH_LATEST_RATES_SUCCESS = 'FETCH_LATEST_RATES';
export const FETCH_LATEST_RATES_ERROR = 'FETCH_LATEST_RATES_ERROR';
