export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR';

export const FETCH_LATEST_RATES_SUCCESS = 'FETCH_LATEST_RATES';
export const FETCH_LATEST_RATES_ERROR = 'FETCH_LATEST_RATES_ERROR';
