export const FETCH_LATEST_RATES_SUCCESS = 'FETCH_LATEST_RATES';
export const FETCH_LATEST_RATES_ERROR = 'FETCH_LATEST_RATES_ERROR';

export const CONVERT_CURRENCY_SUCCESS = 'CONVERT_CURRENCY_SUCCESS';
export const CONVERT_CURRENCY_ERROR = 'CONVERT_CURRENCY_ERROR';
